version: "3"
services:
  postgres:
    container_name: listvideo_database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: lv_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d

volumes:
  pgdata:
