spring:
  config:
    import: optional:file:.env.dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  server:
    error:
      include-stacktrace: never
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${SPRING_JPA_HIBERNATE_FORMAT_SQL:false}
        hbm2ddl:
          auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
# === FEIGN ===
feign:
  client:
    mercadopago:
      url: ${MERCADO_PAGO_API_URL}
      token: ${MERCADO_PAGO_SECRET_TOKEN}
    mailgun:
      url: ${MAILGUN_API_URL}
      apiKey: ${MAILGUN_API_KEY}
      username: ${MAILGUN_API_USERNAME}
services:
  mailgun:
    email:
      domain: ${MAILGUN_DOMAIN}
      from-address: ${MAILGUN_FROM_ADDRESS}
# === LOG ===
logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: DEBUG
# === APP ===
app:
  account_activation_url: ${ACCOUNT_ACTIVATION_URL}
  password_recovery_url: ${PASSWORD_RECOVERY_URL}
  auto_activate_users: ${AUTO_ACTIVATE_USERS}
  features:
    password_reset_email:
      enabled: ${FEATURE_PASSWORD_RESET_EMAIL_ENABLED:false}
    activation_resend_email:
      enabled: ${FEATURE_ACTIVATION_RESEND_EMAIL_ENABLED:false}
  cookie:
    name: ${AUTH_COOKIE_NAME}
    secure: ${AUTH_COOKIE_SECURE}
    same-site: ${AUTH_COOKIE_SAMESITE}
  jwt:
    token:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER}
    expiration-time-in-hours: ${JWT_EXPIRATION_TIME_IN_HOURS}
